//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolChat.ConsoleTest.AuthServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthServiceReference.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        CoolChat.AuthService.Models.User Register(CoolChat.AuthService.Models.RegisterModel registerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Register", ReplyAction="http://tempuri.org/IAuthService/RegisterResponse")]
        System.Threading.Tasks.Task<CoolChat.AuthService.Models.User> RegisterAsync(CoolChat.AuthService.Models.RegisterModel registerModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetToken", ReplyAction="http://tempuri.org/IAuthService/GetTokenResponse")]
        string GetToken(CoolChat.AuthService.Models.LoginModel loginModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/GetToken", ReplyAction="http://tempuri.org/IAuthService/GetTokenResponse")]
        System.Threading.Tasks.Task<string> GetTokenAsync(CoolChat.AuthService.Models.LoginModel loginModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/CheckToken", ReplyAction="http://tempuri.org/IAuthService/CheckTokenResponse")]
        bool CheckToken(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/CheckToken", ReplyAction="http://tempuri.org/IAuthService/CheckTokenResponse")]
        System.Threading.Tasks.Task<bool> CheckTokenAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : CoolChat.ConsoleTest.AuthServiceReference.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<CoolChat.ConsoleTest.AuthServiceReference.IAuthService>, CoolChat.ConsoleTest.AuthServiceReference.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CoolChat.AuthService.Models.User Register(CoolChat.AuthService.Models.RegisterModel registerModel) {
            return base.Channel.Register(registerModel);
        }
        
        public System.Threading.Tasks.Task<CoolChat.AuthService.Models.User> RegisterAsync(CoolChat.AuthService.Models.RegisterModel registerModel) {
            return base.Channel.RegisterAsync(registerModel);
        }
        
        public string GetToken(CoolChat.AuthService.Models.LoginModel loginModel) {
            return base.Channel.GetToken(loginModel);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenAsync(CoolChat.AuthService.Models.LoginModel loginModel) {
            return base.Channel.GetTokenAsync(loginModel);
        }
        
        public bool CheckToken(string token) {
            return base.Channel.CheckToken(token);
        }
        
        public System.Threading.Tasks.Task<bool> CheckTokenAsync(string token) {
            return base.Channel.CheckTokenAsync(token);
        }
    }
}
